--- #YAML:1.0
name:               Text-FixedWidth-Helper
version:            0.02
abstract:           Create or verify samples of fixed-width data
author:
    - James E Keenan (jkeenan@cpan.org)
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:               0
    Cwd:                0
    IO::CaptureOutput:  0
    IO::File:           0
    Scalar::Util:       0
    Test::Simple:       0.44
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
